# Corrected Configuration for Codemagic CI/CD
# For iOS simulator and Android debug builds

workflows:
  cross-platform-workflow:
    name: iOS and Android Workflow
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    scripts:
      - name: Set iOS Simulator destination
        script: |
          DESTINATION="platform=iOS Simulator,name=iPhone 12,OS=latest"
          echo $DESTINATION > /tmp/simulator_destination.txt
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --repo-update
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build iOS for Simulator
        script: |
          flutter build ios --debug --simulator --no-codesign
      - name: Xcode build for simulator
        script: |
          DESTINATION=$(cat /tmp/simulator_destination.txt)
          xcodebuild -workspace "ios/Runner.xcworkspace" \
                     -scheme "Runner" \
                     -destination "$DESTINATION" \
                     -configuration Debug \
                     build \
                     ONLY_ACTIVE_ARCH=YES \
                     CODE_SIGN_IDENTITY="" \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGNING_ALLOWED=NO
      - name: Build Android APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/ios/iphonesimulator/Runner.app
      - build/app/outputs/flutter-apk/app-debug.apk
